### 전체 유저 목록 조회
GET http://localhost:3000/users

###

### 특정 유저 조회 (ID: 1)
GET http://localhost:3000/users/2

###

### Health Check
GET http://localhost:3000/dbtest

###

### 유저 생성
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test3@example.com",
  "nickname": "testuser22",
  "password": "password123"
}